remote_theme: pages-themes/leap-day@v0.2.0
url: https://asaragga.github.io/FinCalc
plugins:
- jekyll-remote-theme 
title: Law & Money Matters ðŸ¥‚
description: Financial Analysis and Computation for Solicitors
